import { useEffect, useState } from 'react'
import { Plus, RefreshCw, Trash2 } from 'lucide-react'

type Profile = { name: string; description: string; instruction: string; model: string; tools: string[]; max_turns: number; scope: { lake_id: string; all_resources?: boolean; resource_ids?: string[]; project_root?: string }; enabled: boolean }
type Task = { id: string; name: string; model: string; status: string; checkpoint_available: boolean; resume_available?: boolean; workflow_run_id?: string; scope_json: string; updated_at: string }
type Lake = { id: string; name: string }
type Project = { id: string; lake_id: string; lake: string; name: string; path: string }
type Resource = { id: string; name: string; kind: string }
const api = () => { const value = window.go?.main?.App; if (!value) throw new Error('桌面桥未就绪'); return value }
const blank = (): Profile => ({ name: 'lake_specialist_', description: '', instruction: '', model: '', tools: ['lake_code_read', 'lake_code_search'], max_turns: 12, scope: { lake_id: '', resource_ids: [] }, enabled: false })

export default function SpecialistPanel({ onResume }: { onResume: (id: string, retry: boolean) => Promise<void> }) {
  const [profiles, setProfiles] = useState<Profile[]>([]), [models, setModels] = useState<{ name: string }[]>([]), [lakes, setLakes] = useState<Lake[]>([]), [projects, setProjects] = useState<Project[]>([]), [resources, setResources] = useState<Resource[]>([])
  const [draft, setDraft] = useState<Profile>(blank), [selected, setSelected] = useState(''), [tasks, setTasks] = useState<Task[]>([]), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
  const load = async () => {
    const [settings, lakeList, projectList, taskList] = await Promise.all([api().Settings('{"action":"get"}'), api().ListLakes(), api().ListCodeProjects(), api().ListSpecialistTasks()])
    const data = JSON.parse(settings); setProfiles(data.specialists ?? []); setModels(data.models); setLakes(JSON.parse(lakeList)); setProjects(JSON.parse(projectList)); setTasks(JSON.parse(taskList))
  }
  useEffect(() => { void load().catch(e => setError(String(e))) }, [])
  useEffect(() => { const lake = lakes.find(l => l.id === draft.scope.lake_id); if (lake) void api().ListResources(lake.name).then(v => setResources(JSON.parse(v))).catch(e => setError(String(e))); else setResources([]) }, [draft.scope.lake_id, lakes])
  const action = async (request: object, message: string) => { setBusy(true); setError(''); setNotice(''); try { await api().Settings(JSON.stringify(request)); await load(); setNotice(message) } catch (e) { setError(String(e)) } finally { setBusy(false) } }
  return <>
    <div className="settings-heading"><div><h1>自定义专员</h1><p>指定独立模型、工具白名单和所属湖。修改在新会话生效，停用后旧会话调用也会被拒绝。</p></div><button className="settings-secondary" onClick={() => { setSelected(''); setDraft(blank()) }}><Plus size={15} />添加专员</button></div>
    {error && <div role="alert" className="settings-alert error">{error}</div>}{notice && <div className="settings-alert success">{notice}</div>}
    <div className="settings-split"><div className="settings-list">{profiles.map(p => <button key={p.name} className={p.name === selected ? 'active' : ''} onClick={() => { setSelected(p.name); setDraft(p); setNotice('') }}><span><strong>{p.name}</strong><small>{p.model} · {p.enabled ? '已启用' : '已停用'}</small></span></button>)}</div>
      <div className="settings-card"><label>专员标识<input value={draft.name} disabled={!!selected} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>任务说明<input value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><label>独立模型<select value={draft.model} onChange={e => setDraft({ ...draft, model: e.target.value })}><option value="">选择模型</option>{models.map(m => <option key={m.name}>{m.name}</option>)}</select></label>
        <label>所属湖<select value={draft.scope.lake_id} onChange={e => setDraft({ ...draft, scope: { lake_id: e.target.value, resource_ids: [] } })}><option value="">选择湖</option>{lakes.map(l => <option value={l.id} key={l.id}>{l.name}</option>)}</select></label>
        <label>代码项目<select value={draft.scope.project_root ?? ''} onChange={e => setDraft({ ...draft, scope: { ...draft.scope, project_root: e.target.value || undefined } })}><option value="">不使用代码项目</option>{projects.filter(p => p.lake_id === draft.scope.lake_id).map(p => <option value={p.path} key={p.id}>{p.name} · {p.path}</option>)}</select></label>
        <label className="settings-check"><input type="checkbox" checked={draft.scope.all_resources ?? false} onChange={e => setDraft({ ...draft, scope: { ...draft.scope, all_resources: e.target.checked } })} />允许当前会话已授权的所有资源</label>
        {!draft.scope.all_resources && resources.map(r => <label className="settings-check" key={r.id}><input type="checkbox" checked={draft.scope.resource_ids?.includes(r.id) ?? false} onChange={e => setDraft({ ...draft, scope: { ...draft.scope, resource_ids: e.target.checked ? [...(draft.scope.resource_ids ?? []), r.id] : draft.scope.resource_ids?.filter(id => id !== r.id) } })} />{r.name} · {r.kind}</label>)}
        <label>工具白名单（每行一个工具名）<textarea rows={5} value={draft.tools.join('\n')} onChange={e => setDraft({ ...draft, tools: e.target.value.split('\n') })} /></label><p className="settings-help">例如 lake_code_read、lake_ssh、lake_k8s_get、lake_database_inspect，或会话中已加载的 mcp_* 工具。专员不能递归分派。</p>
        <label>最大轮数<input type="number" min={1} max={32} value={draft.max_turns} onChange={e => setDraft({ ...draft, max_turns: Number(e.target.value) })} /></label><label>专员提示词<textarea rows={6} value={draft.instruction} onChange={e => setDraft({ ...draft, instruction: e.target.value })} /></label><label className="settings-check"><input type="checkbox" checked={draft.enabled} onChange={e => setDraft({ ...draft, enabled: e.target.checked })} />启用</label>
        <div className="settings-actions"><button className="primary" disabled={busy} onClick={() => void action({ action: 'specialist_save', specialist: { ...draft, tools: draft.tools.map(t => t.trim()).filter(Boolean) } }, '专员已保存')}>保存专员</button>{selected && <button className="settings-danger" disabled={busy} onClick={() => { if (window.confirm(`删除 ${selected}？已有任务仍保留。`)) void action({ action: 'specialist_delete', name: selected }, '专员已删除') }}><Trash2 size={15} /></button>}</div>
      </div></div>
    <section className="settings-card"><div className="settings-heading"><h2>最近专员任务</h2><button className="settings-secondary" onClick={() => void load().catch(e => setError(String(e)))}><RefreshCw size={14} />刷新</button></div><p className="settings-help">恢复需切换到原湖并绑定原项目。已完成步骤不会重复执行；结果未知的写操作默认阻断。</p>{tasks.map(t => <div className="extension-row" key={t.id}><div><strong>{t.name} · {t.status}</strong><span>{lakes.find(l => l.id === JSON.parse(t.scope_json).lake_id)?.name ?? '原湖'} · {JSON.parse(t.scope_json).project_root ?? ''} · {t.id} · {t.model} · {new Date(t.updated_at).toLocaleString()}</span></div>{t.workflow_run_id && <span>工作流运行 {t.workflow_run_id}；恢复入口在工作流运行记录</span>}{t.status !== 'completed' && t.checkpoint_available && t.resume_available !== false && <div className="settings-actions"><button disabled={busy} onClick={() => void onResume(t.id, false).catch(e => setError(String(e)))}>恢复</button><button disabled={busy} onClick={() => { if (window.confirm('已核对外部结果，确认允许重试结果未知的写操作？写工具仍需重新批准。')) void onResume(t.id, true).catch(e => setError(String(e))) }}>核对后重试写操作</button></div>}</div>)}{tasks.length === 0 && <p>暂无任务。</p>}</section>
  </>
}
