export type ReportTone = 'good' | 'warning' | 'critical' | 'info' | 'unknown'
export type ReportNode = { id: string; label: string; status: 'pending' | 'running' | 'completed' | 'failed' | 'unknown' | 'skipped' | 'cancelled'; detail?: string }
export type ReportFlow = { nodes: ReportNode[]; edges?: { from: string; to: string }[] }
export type VisualReport = {
  title: string; summary: string; tone: ReportTone; scope?: string
  metrics?: { label: string; value: string; hint?: string; tone: ReportTone }[]
  charts?: { title: string; kind: 'distribution' | 'bar'; unit?: string; segments: { label: string; value: number; tone: ReportTone }[] }[]
  table?: { title: string; columns: string[]; rows: { cells: string[]; tone: ReportTone }[] }
  findings?: { title: string; detail: string; next_step?: string; tone: ReportTone }[]
  flow?: ReportFlow; sources?: string[]; ui?: ReportUI
}

// Compatibility for reports generated by the old workflow completion hook.
// These contain execution bookkeeping, rather than inspection data.
export function isWorkflowExecutionReport(report: VisualReport): boolean {
  return !!report.flow && !report.table && !report.charts?.length && !report.findings?.length &&
    report.title.endsWith(' · 执行结果') && !!report.scope?.startsWith('本次运行快照') &&
    report.metrics?.length === 3 && report.metrics.every((metric, index) => metric.label === ['执行步骤', '已完成', '需核对'][index])
}

export function isReportFormattingError(text: string): boolean {
  return /tool\[name:lake_visual_report\b/.test(text) && /(?:tool input (?:violates schema|must be a JSON object)|图形化报告|动态界面)/.test(text)
}

const tones = new Set(['good', 'warning', 'critical', 'info', 'unknown'])
const statuses = new Set(['pending', 'running', 'completed', 'failed', 'unknown', 'skipped', 'cancelled'])
const text = (v: unknown, limit: number, required = true): v is string => typeof v === 'string' && [...v].length <= limit && !v.includes('\0') && (!required || !!v.trim())
const optional = (v: unknown, limit: number) => v === undefined || text(v, limit, false)
const list = (v: unknown, limit: number): v is unknown[] => v === undefined || (Array.isArray(v) && v.length <= limit)
const object = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v)
const tone = (v: unknown) => typeof v === 'string' && tones.has(v)

// Events may be historical or supplied by a remote read-only endpoint. Reject
// malformed cards instead of letting an invalid table/graph crash the timeline.
export function parseVisualReport(value: unknown): VisualReport | null {
  if (typeof value === 'string') { if (value.length > 65536) return null; try { value = JSON.parse(value) } catch { return null } }
  if (!object(value) || !text(value.title, 80) || !text(value.summary, 280) || !tone(value.tone) || !optional(value.scope, 200)) return null
  if (!list(value.metrics, 8) || !list(value.charts, 3) || !list(value.findings, 8) || !list(value.sources, 8)) return null
  if (!value.metrics?.length && !value.charts?.length && !value.findings?.length && value.table === undefined && value.flow === undefined) return null
  if (value.metrics?.some(m => !object(m) || !text(m.label, 40) || !text(m.value, 40) || !optional(m.hint, 100) || !tone(m.tone))) return null
  if (value.charts?.some(c => !object(c) || !text(c.title, 80) || !optional(c.unit, 20) || !['distribution', 'bar'].includes(String(c.kind)) || !Array.isArray(c.segments) || !c.segments.length || c.segments.length > 16 || c.segments.some(s => !object(s) || !text(s.label, 60) || !tone(s.tone) || typeof s.value !== 'number' || !Number.isFinite(s.value) || s.value < 0 || s.value > 1e12) || (c.kind === 'distribution' && c.segments.reduce((sum, s) => sum + (s as { value: number }).value, 0) === 0))) return null
  if (value.findings?.some(f => !object(f) || !text(f.title, 80) || !text(f.detail, 500) || !optional(f.next_step, 200) || !tone(f.tone))) return null
  if (value.sources?.some(s => !text(s, 300))) return null
  if (value.table !== undefined) {
    const t = value.table
    if (!object(t) || !text(t.title, 80) || !Array.isArray(t.columns) || !t.columns.length || t.columns.length > 6 || t.columns.some(c => !text(c, 40)) || !Array.isArray(t.rows) || t.rows.length > 100 || t.rows.some(r => !object(r) || !tone(r.tone) || !Array.isArray(r.cells) || r.cells.length !== (t.columns as unknown[]).length || r.cells.some(c => !text(c, 240, false)))) return null
  }
  if (value.flow !== undefined) {
    const f = value.flow
    if (!object(f) || !Array.isArray(f.nodes) || !f.nodes.length || f.nodes.length > 64 || !list(f.edges, 128)) return null
    if (f.nodes.some(n => !object(n) || !text(n.id, 128) || !text(n.label, 80) || !statuses.has(String(n.status)) || !optional(n.detail, 500))) return null
    const nodes = f.nodes as ReportNode[]
    if (new Set(nodes.map(n => n.id)).size !== nodes.length) return null
    const edges = f.edges as ReportFlow['edges']
    if (edges?.some(e => !object(e) || !nodes.some(n => n.id === e.from) || !nodes.some(n => n.id === e.to))) return null
    if (!flowLayout({ nodes, edges })) return null
  }
  if (value.ui !== undefined && !validateReportUI(value.ui, value as VisualReport)) return { ...value, ui: undefined } as VisualReport
  return value as VisualReport
}

export function flowLayout(flow: ReportFlow) {
  const depth = new Map<string, number>()
  const remaining = new Set(flow.nodes.map(n => n.id))
  const edges = flow.edges ?? []
  while (remaining.size) {
    const available = [...remaining].filter(id => edges.filter(e => e.to === id).every(e => depth.has(e.from)))
    if (!available.length) return null
    for (const id of available) { depth.set(id, Math.max(0, ...edges.filter(e => e.to === id).map(e => (depth.get(e.from) ?? 0) + 1))); remaining.delete(id) }
  }
  const layers: ReportNode[][] = []
  for (const node of flow.nodes) { const d = depth.get(node.id)!; (layers[d] ??= []).push(node) }
  const width = Math.max(1, ...layers.map(layer => layer.length)) * 200 + 24
  const positions = new Map<string, { x: number; y: number }>()
  layers.forEach((layer, index) => layer.forEach((node, col) => positions.set(node.id, { x: (width - layer.length * 200) / 2 + col * 200 + 10, y: 16 + index * 112 })))
  return { width, height: layers.length * 112, positions }
}

export const reportToneLabel: Record<ReportTone, string> = { good: '正常', warning: '需关注', critical: '异常', info: '概览', unknown: '待确认' }
export const nodeStatusLabel: Record<ReportNode['status'], string> = { pending: '待执行', running: '执行中', completed: '已完成', failed: '失败', unknown: '结果未知', skipped: '已跳过', cancelled: '已取消' }
export const nodeTone = (status: ReportNode['status']): ReportTone => status === 'failed' ? 'critical' : status === 'unknown' ? 'warning' : status === 'completed' ? 'good' : status === 'running' ? 'info' : 'unknown'
import { validateReportUI, type ReportUI } from './reportUI.ts'
