// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCodeProject(arg1:string,arg2:string):Promise<string>;

export function AddDatabaseResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string,arg8:string,arg9:string):Promise<string>;

export function AddK8sResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function Approve(arg1:string,arg2:boolean):Promise<void>;

export function ArchiveConversation(arg1:string):Promise<void>;

export function Ask(arg1:string,arg2:string):Promise<void>;

export function AskWithImages(arg1:string,arg2:string,arg3:Array<main.ImageAttachment>):Promise<void>;

export function AuthorizeResource(arg1:string,arg2:boolean):Promise<void>;

export function BindConversationProject(arg1:string,arg2:string):Promise<string>;

export function CreateConversation(arg1:string):Promise<string>;

export function CurrentLake():Promise<string>;

export function DeleteMemory(arg1:string):Promise<string>;

export function ExtensionStatus(arg1:string):Promise<string>;

export function GetConversation(arg1:string):Promise<string>;

export function GetMemory():Promise<string>;

export function GetPermissions():Promise<string>;

export function GetWorkflowRun(arg1:string):Promise<string>;

export function ListAllResources():Promise<string>;

export function ListArchivedConversations():Promise<string>;

export function ListCodeProjects():Promise<string>;

export function ListConversations():Promise<string>;

export function ListKubeContexts(arg1:string):Promise<string>;

export function ListLakes():Promise<string>;

export function ListModels():Promise<string>;

export function ListResources(arg1:string):Promise<string>;

export function ListWorkflowRuns(arg1:string):Promise<string>;

export function ListWorkflows():Promise<string>;

export function PickCodeProjectDirectory():Promise<string>;

export function PickKubeconfigFile():Promise<string>;

export function RenameConversation(arg1:string,arg2:string):Promise<string>;

export function RestoreConversation(arg1:string):Promise<void>;

export function RunWorkflow(arg1:string,arg2:string,arg3:main.WorkflowRunRequest):Promise<void>;

export function SetMemoryEnabled(arg1:boolean):Promise<string>;

export function SetPermission(arg1:string,arg2:boolean):Promise<string>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<string>;

export function SetWorkspaceHookEnabled(arg1:string,arg2:boolean):Promise<string>;

export function Settings(arg1:string):Promise<string>;

export function StartConversation(arg1:string):Promise<void>;

export function StopConversation():Promise<void>;

export function UseLake(arg1:string):Promise<void>;

export function UseModel(arg1:string):Promise<void>;
