// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCodeProject(arg1, arg2) {
  return window['go']['main']['App']['AddCodeProject'](arg1, arg2);
}

export function AddDatabaseResource(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['AddDatabaseResource'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function AddK8sResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddK8sResource'](arg1, arg2, arg3, arg4, arg5);
}

export function Approve(arg1, arg2) {
  return window['go']['main']['App']['Approve'](arg1, arg2);
}

export function ArchiveConversation(arg1) {
  return window['go']['main']['App']['ArchiveConversation'](arg1);
}

export function Ask(arg1, arg2) {
  return window['go']['main']['App']['Ask'](arg1, arg2);
}

export function AskWithImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['AskWithImages'](arg1, arg2, arg3);
}

export function AuthorizeResource(arg1, arg2) {
  return window['go']['main']['App']['AuthorizeResource'](arg1, arg2);
}

export function BindConversationProject(arg1, arg2) {
  return window['go']['main']['App']['BindConversationProject'](arg1, arg2);
}

export function CreateConversation(arg1) {
  return window['go']['main']['App']['CreateConversation'](arg1);
}

export function CurrentLake() {
  return window['go']['main']['App']['CurrentLake']();
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function ExtensionStatus(arg1) {
  return window['go']['main']['App']['ExtensionStatus'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetMemory() {
  return window['go']['main']['App']['GetMemory']();
}

export function GetPermissions() {
  return window['go']['main']['App']['GetPermissions']();
}

export function GetWorkflowRun(arg1) {
  return window['go']['main']['App']['GetWorkflowRun'](arg1);
}

export function ListAllResources() {
  return window['go']['main']['App']['ListAllResources']();
}

export function ListArchivedConversations() {
  return window['go']['main']['App']['ListArchivedConversations']();
}

export function ListCodeProjects() {
  return window['go']['main']['App']['ListCodeProjects']();
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListKubeContexts(arg1) {
  return window['go']['main']['App']['ListKubeContexts'](arg1);
}

export function ListLakes() {
  return window['go']['main']['App']['ListLakes']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListResources(arg1) {
  return window['go']['main']['App']['ListResources'](arg1);
}

export function ListWorkflowRuns(arg1) {
  return window['go']['main']['App']['ListWorkflowRuns'](arg1);
}

export function ListWorkflows() {
  return window['go']['main']['App']['ListWorkflows']();
}

export function PickCodeProjectDirectory() {
  return window['go']['main']['App']['PickCodeProjectDirectory']();
}

export function PickKubeconfigFile() {
  return window['go']['main']['App']['PickKubeconfigFile']();
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function RestoreConversation(arg1) {
  return window['go']['main']['App']['RestoreConversation'](arg1);
}

export function RunWorkflow(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunWorkflow'](arg1, arg2, arg3);
}

export function SetMemoryEnabled(arg1) {
  return window['go']['main']['App']['SetMemoryEnabled'](arg1);
}

export function SetPermission(arg1, arg2) {
  return window['go']['main']['App']['SetPermission'](arg1, arg2);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2);
}

export function SetWorkspaceHookEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspaceHookEnabled'](arg1, arg2);
}

export function Settings(arg1) {
  return window['go']['main']['App']['Settings'](arg1);
}

export function StartConversation(arg1) {
  return window['go']['main']['App']['StartConversation'](arg1);
}

export function StopConversation() {
  return window['go']['main']['App']['StopConversation']();
}

export function UseLake(arg1) {
  return window['go']['main']['App']['UseLake'](arg1);
}

export function UseModel(arg1) {
  return window['go']['main']['App']['UseModel'](arg1);
}
