export const lakeCatalogCopy = {
  "zh-CN": {
    title: "资源管理",
    back: "返回聊天",
    intro: "按业务系统组织软件运维资产。资源登记不代表已连接或正在监控。",
    catalogEyebrow: "LAKE 资源目录",
    lakes: "湖",
    lakeNavigation: "湖导航",
    lakeCount: (count: number) => `${count} 个湖`,
    currentLake: "当前湖",
    createLake: "创建湖",
    createLakeIntro: "创建一个业务系统或项目，并绑定它使用的项目目录。",
    lakeName: "湖名称",
    lakeDescription: "湖说明（可选）",
    projectDirectory: "项目目录",
    chooseProjectDirectory: "选择本地项目目录",
    chooseOpenProject: "或选择已打开的项目",
    chooseProjectFirst: "先选择项目目录，才能创建或绑定湖。",
    bindProject: "绑定项目目录",
    bindProjectHint: "这个湖尚未绑定项目目录，绑定后才能在此湖中展开 Agent 会话。",
    boundProject: "已绑定项目",
    unboundProject: "未绑定项目目录",
    emptyLakes: "还没有湖，先创建一个业务系统或项目。",
    resources: "资源",
    resourceList: "资源清单",
    registeredResources: "全部资源",
    resourceResults: (visible: number, total: number) =>
      visible === total ? `共 ${total} 项` : `显示 ${visible} / ${total} 项`,
    catalogActions: "湖资源操作",
    searchResources: "搜索资源名称或说明",
    allKinds: "全部类型",
    allEnvironments: "全部环境",
    clearFilters: "清除筛选",
    noMatches: "没有匹配的资源",
    noMatchesHint: "尝试调整关键词、资源类型或环境筛选。",
    noResourceDescription: "暂无说明",
    emptyResourcesTitle: "从第一项资源开始",
    emptyResources: "这个湖还没有资源。可以登记新资源，或加入已有资源。",
    newResource: "登记新资源",
    newResourceIntro: "登记资源的基本信息。这里不会采集凭据，也不会建立连接。",
    existingResource: "加入已有资源",
    existingResourceIntro: "复用全局目录中的资源，不会创建重复资源记录。",
    backToResources: "返回资源清单",
    resourceName: "资源名称",
    resourceKind: "类型",
    environment: "环境",
    resourceDescription: "说明（可选）",
    selectResource: "选择资源",
    addToLake: "加入当前湖",
    loading: "正在加载…",
    saving: "正在保存…",
    noExisting: "没有可加入的已有资源。",
    loadFailed: "读取资源目录失败",
    saveFailed: "保存失败",
    service: "服务",
    host: "主机",
    "kubernetes-cluster": "Kubernetes 集群",
    database: "数据库",
    production: "生产",
    staging: "预发",
    development: "开发",
    other: "其他",
    sshTitle: "SSH 会话",
    sshIntro:
      "从这台主机打开临时终端。主机指纹仍在终端确认；已保存密码在标准提示出现时自动填写一次。",
    sshManage: "管理 SSH",
    sshHost: "主机地址",
    sshPort: "端口",
    sshUsername: "用户名",
    sshPrivateKeyPath: "私钥路径",
    sshOptionalKey: "可选；留空使用 SSH Agent 或默认密钥",
    sshSave: "保存连接配置",
    sshConnect: "打开 SSH 终端",
    sshSaveBeforeConnect: "先保存修改，再打开终端",
    sshPassword: "SSH 密码",
    sshPasswordHint:
      "应用级加密保存（非系统钥匙串）；页面不会回显。标准密码提示时自动填写一次，其他提示仍可在终端手输。",
    sshPasswordSavedPlaceholder: "已保存；留空保持不变",
    sshSavePassword: "保存密码",
    sshDeletePassword: "删除已存密码",
    sshPasswordSaved: "已保存密码",
    sshPasswordMissing: "未保存密码，可在终端手动输入",
    sshSaveBeforePassword: "先保存主机地址、端口和用户名，再保存密码。",
    sshSessions: "SSH 会话",
    sshSession: "终端",
    sshDisconnect: "断开终端",
    sshSessionHint: "离开本页会断开这些终端；不会创建 Agent 任务。",
    opening: "启动中",
    running: "运行中",
    exited: "已结束",
    failed: "失败",
  },
  "en-US": {
    title: "Resource management",
    back: "Back to chat",
    intro:
      "Organize software operations assets by system. Registration does not connect or monitor them.",
    catalogEyebrow: "LAKE RESOURCE CATALOG",
    lakes: "Lakes",
    lakeNavigation: "Lake navigation",
    lakeCount: (count: number) => `${count} ${count === 1 ? "lake" : "lakes"}`,
    currentLake: "Current lake",
    createLake: "Create lake",
    createLakeIntro: "Create a system or project and bind the project directory it uses.",
    lakeName: "Lake name",
    lakeDescription: "Description (optional)",
    projectDirectory: "Project directory",
    chooseProjectDirectory: "Choose local project directory",
    chooseOpenProject: "Or choose an open project",
    chooseProjectFirst: "Choose a project directory before creating or binding a lake.",
    bindProject: "Bind project directory",
    bindProjectHint:
      "This lake has no project directory yet. Bind one to open Agent sessions here.",
    boundProject: "Bound project",
    unboundProject: "No project directory bound",
    emptyLakes: "No lakes yet. Create one for a system or project.",
    resources: "Resources",
    resourceList: "Resource catalog",
    registeredResources: "All resources",
    resourceResults: (visible: number, total: number) =>
      visible === total ? `${total} total` : `Showing ${visible} of ${total}`,
    catalogActions: "Lake resource actions",
    searchResources: "Search names or descriptions",
    allKinds: "All types",
    allEnvironments: "All environments",
    clearFilters: "Clear filters",
    noMatches: "No matching resources",
    noMatchesHint: "Try another keyword, resource type, or environment.",
    noResourceDescription: "No description",
    emptyResourcesTitle: "Add the first resource",
    emptyResources: "No resources in this lake. Register one or add an existing resource.",
    newResource: "Register new resource",
    newResourceIntro:
      "Register basic resource information. This does not collect credentials or connect to it.",
    existingResource: "Add existing resource",
    existingResourceIntro: "Reuse a resource from the global catalog without creating a duplicate.",
    backToResources: "Back to resources",
    resourceName: "Resource name",
    resourceKind: "Type",
    environment: "Environment",
    resourceDescription: "Description (optional)",
    selectResource: "Select resource",
    addToLake: "Add to lake",
    loading: "Loading…",
    saving: "Saving…",
    noExisting: "No existing resources available to add.",
    loadFailed: "Could not load resource catalog",
    saveFailed: "Could not save",
    service: "Service",
    host: "Host",
    "kubernetes-cluster": "Kubernetes cluster",
    database: "Database",
    production: "Production",
    staging: "Staging",
    development: "Development",
    other: "Other",
    sshTitle: "SSH sessions",
    sshIntro:
      "Open a temporary terminal for this host. Confirm host keys in the terminal; a saved password is sent once when a standard prompt appears.",
    sshManage: "Manage SSH",
    sshHost: "Host address",
    sshPort: "Port",
    sshUsername: "Username",
    sshPrivateKeyPath: "Private key path",
    sshOptionalKey: "Optional; leave blank for SSH Agent or default keys",
    sshSave: "Save connection profile",
    sshConnect: "Open SSH terminal",
    sshSaveBeforeConnect: "Save changes before opening a terminal",
    sshPassword: "SSH password",
    sshPasswordHint:
      "Encrypted by the app (not the OS keychain), never shown again. Sent once at a standard password prompt; other prompts remain interactive.",
    sshPasswordSavedPlaceholder: "Saved; leave blank to keep it",
    sshSavePassword: "Save password",
    sshDeletePassword: "Delete saved password",
    sshPasswordSaved: "Password saved",
    sshPasswordMissing: "No password saved; you can enter it in the terminal",
    sshSaveBeforePassword: "Save the host, port, and username before saving a password.",
    sshSessions: "SSH sessions",
    sshSession: "Terminal",
    sshDisconnect: "Disconnect terminal",
    sshSessionHint: "Leaving this page disconnects these terminals; no Agent task is created.",
    opening: "Starting",
    running: "Running",
    exited: "Exited",
    failed: "Failed",
  },
} as const;
